baseURL = "https://nhattienblog.netlify.app"
theme = 'cozy-garden'
title = "Tien's Garden"
languageCode = "en-US"

ignoreFiles = [
    "/content/.obsidian/*",
    "/content/template/*",
    "/content/manage/*",
]

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

enableEmoji = true


[params]
  favicon = "/images/favicon.png"
  dateFormat = "02/01/2006"

[markup]
  [markup.highlight]
    # lineNos = true
    noClasses = false
    lineNumbersInTable = false
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[permalinks]
  [permalinks.page]
    garden = '/garden/:filename/'

[outputs]
  home = ["HTML", "RSS", "JSON"]

